//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "common_plant")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "common_plant_common_danish_name_common_english_name_unique")]
    pub common_danish_name: String,
    #[sea_orm(unique_key = "common_plant_common_danish_name_common_english_name_unique")]
    pub common_english_name: String,
    pub da_wiki_url: String,
    pub image_url: String,
    pub description: String,
    pub gbif_genus_key: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::gbif_genus::Entity",
        from = "Column::GbifGenusKey",
        to = "super::gbif_genus::Column::Key",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GbifGenus,
    #[sea_orm(has_many = "super::growth::Entity")]
    Growth,
}

impl Related<super::gbif_genus::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GbifGenus.def()
    }
}

impl Related<super::growth::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Growth.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
