//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "growth")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub growth_type: String,
    pub age_estimate: Decimal,
    pub height: Decimal,
    pub width: Decimal,
    pub common_plant_id: i32,
    pub created_by: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub active: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::common_plant::Entity",
        from = "Column::CommonPlantId",
        to = "super::common_plant::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CommonPlant,
    #[sea_orm(has_many = "super::gardening_task_growth_assoication::Entity")]
    GardeningTaskGrowthAssoication,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedBy",
        to = "super::user::Column::Uuid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::common_plant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommonPlant.def()
    }
}

impl Related<super::gardening_task_growth_assoication::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GardeningTaskGrowthAssoication.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
