[package]
name = "query-service"
version = "0.1.0"
edition = "2024"

[dependencies]
entity = { path = "../entity" }
infra = { path = "../infra" }
shared = { path = "../shared" }
sea-orm = { workspace = true }
