//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "gbif_genus")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub key: i32,
    pub canonical_name: String,
    pub scientific_name: String,
    pub family: String,
    pub genus: String,
    pub rank: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::common_plant::Entity")]
    CommonPlant,
}

impl Related<super::common_plant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommonPlant.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
