//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::Role;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub active: Option<bool>,
    pub created_at: Option<DateTime>,
    pub pw_hash: String,
    pub role: Option<Role>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::gardening_task::Entity")]
    GardeningTask,
    #[sea_orm(has_many = "super::growth::Entity")]
    Growth,
    #[sea_orm(has_many = "super::session::Entity")]
    Session,
}

impl Related<super::gardening_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GardeningTask.def()
    }
}

impl Related<super::growth::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Growth.def()
    }
}

impl Related<super::session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Session.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
