// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlantRecord = { common_name: string, family: string, wiki_url: string, image_url: string, description: string, in_garden: boolean, };
